Program 2 (Ruby on Rails)/config/routes.rb
Rails.application.routes.draw do

  get 'adminprofile/showadmin'
  resources :recompanies
  devise_for :admins, :controllers => {
      :registrations => "admins/registrations",
      :sessions => "admins/sessions",
      :passwords => "admins/passwords",
      :confirmations => "admins/confirmations",
  }

  devise_scope :admin do
    get 'sign_up', to: 'admins/registrations#new'
    get 'sign_in' , to: 'admins/sessions#new'
    delete 'sign_out', to: 'admins/sessions#destroy'
    resources :admins
  end

  #get 'realtorprofile/houses'

  resources :househunterprofile
  get '/showprofile' => "househunterprofile#showprofile", as: :house_hunter_root
  resources :inquiries
  devise_for :house_hunters,  controllers: {sessions: 'house_hunters/sessions'}

  resources :house_hunters
  devise_for :realtors
  resources :houses
   # get '/houses' => "house#index", as: :realtor_root
  # get '/realtorprofile/:current_realtor_id' => "realtorprofile#show", as: :realtor_root
  get '/houses' => "houses#index", as: :realtor_root
  #get '/houses' => "houses#index", as: :house_hunter_root
  #get '/index' => '/app/views/'
  resources :realtorprofile

  get '/admins' => "admins#index"


  root :to => redirect('/homepage.html')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/listinquiries' => "inquiries#listinquiries"
end

Program 2 (Ruby on Rails)/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div>
    <% if realtor_signed_in? %>
      <li>
        <%= link_to('Logout', destroy_realtor_session_path, method: :delete) %>
      </li>
    <% else %>
<!--      <li>-->
        <%#= link_to('Login', new_realtor_session_path)  %>
<!--     </li>-->
    <% end %>
  </div>

  <div>
    <% if house_hunter_signed_in? %>
      Hi! <strong><%=current_house_hunter.name %></strong>
      <li>
        <%= link_to('Logout', destroy_house_hunter_session_path, method: :delete) %>
      </li>
    <% else %>
<!--      <li>-->
        <%#= link_to('Login', new_house_hunter_session_path)  %>
<!--      </li>-->
    <% end %>
  </div>
  <%= yield %>
  </body>
</html>