Program 2 (Ruby on Rails)/config/routes.rb
Rails.application.routes.draw do

  get 'adminprofile/showadmin'
  resources :recompanies
  devise_for :admins, :controllers => {
      :registrations => "admins/registrations",
      :sessions => "admins/sessions",
      :passwords => "admins/passwords",
      :confirmations => "admins/confirmations",
  }

  devise_scope :admin do
    get 'sign_up', to: 'admins/registrations#new'
    get 'sign_in' , to: 'admins/sessions#new'
    delete 'sign_out', to: 'admins/sessions#destroy'
    resources :admins
  end

  #get 'realtorprofile/houses'

  resources :househunterprofile
  get '/showprofile' => "househunterprofile#showprofile", as: :house_hunter_root
  resources :inquiries
  devise_for :house_hunters,  controllers: {sessions: 'house_hunters/sessions'}

  resources :house_hunters
  devise_for :realtors
  resources :houses
   # get '/houses' => "house#index", as: :realtor_root
  # get '/realtorprofile/:current_realtor_id' => "realtorprofile#show", as: :realtor_root
  get '/houses' => "houses#index", as: :realtor_root
  #get '/houses' => "houses#index", as: :house_hunter_root
  #get '/index' => '/app/views/'
  resources :realtorprofile

  get '/admins' => "admins#index"


  root :to => redirect('/homepage.html')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/listinquiries' => "inquiries#listinquiries"
end

Program 2 (Ruby on Rails)/app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]
  # before_action :check_current_user

  #before_action :set_current_user

  # GET /houses
  # GET /houses.json
  def index
    # @current_user ||= current_realtor || current_house_hunter
    # binding.irb
    @houses = House.all # @current_user.houses
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  def inquiries

  end


  def realtorhouses

  end

  # GET /houses/new
  def new
    #@house = House.new
    @house= current_realtor.houses.build
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house= current_realtor.houses.build(house_params)


    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:companyid, :location, :sqf, :year, :style, :price, :floors, :basement, :owner, :contact, :potentialbuyers)
    end
end

Program 2 (Ruby on Rails)/app/helpers/houses_helper.rb
module HousesHelper
end

Program 2 (Ruby on Rails)/app/views/houses/_form.html.erb
<%= form_with(model: house, local: true) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :companyid %>
    <%= form.text_field :companyid %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :sqf %>
    <%= form.text_field :sqf %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :floors %>
    <%= form.text_field :floors %>
  </div>

  <div class="field">
    <%= form.label :basement %>
    <%= form.check_box :basement %>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.text_field :owner %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :potentialbuyers %>
    <%= form.text_field :potentialbuyers %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Program 2 (Ruby on Rails)/app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

Program 2 (Ruby on Rails)/app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<!--<p><strong>Refine your house hunt</strong></p>

<#%= form_with model: @houses, url:house_url do |f| %>
  <p><b>Price Range</b></p>
   $1500<#%= f.range_field(:price, nil , in: 1500..10000) %>$10,000

  <p><b>Area</b></p>
    750 sqft<#%= f.range_field(:sqf, nil , in: 750..5000) %>5000 sqft

  <p><b>Location</b></p>
  <select name="location">
    <#% @houses.each do |house| %>
      <option value=house.location><#%=house.location %></option>
    <#%end %>
  </select>
  <br><br>
  <#%= f.submit "Refine your results" %>
<#%end %> -->

<h1>Houses</h1>

<table>
  <thead>
    <tr>
      <th>Companyid</th>
      <th>Location</th>
      <th>Sqf</th>
      <th>Year</th>
      <th>Style</th>
      <th>Price</th>
      <th>Floors</th>
      <th>Basement</th>
      <th>Owner</th>
      <th>Contact</th>
      <th>Potentialbuyers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.companyid %></td>
        <td><%= house.location %></td>
        <td><%= house.sqf %></td>
        <td><%= house.year %></td>
        <td><%= house.style %></td>
        <td><%= house.price %></td>
        <td><%= house.floors %></td>
        <td><%= house.basement %></td>
        <td><%= house.owner %></td>
        <td><%= house.contact %></td>
        <td><%= house.potentialbuyers %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Inquiry', new_inquiry_path %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

Program 2 (Ruby on Rails)/app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path %>

Program 2 (Ruby on Rails)/app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Companyid:</strong>
  <%= @house.companyid %>
</p>

<p>
  <strong>Location:</strong>
  <%= @house.location %>
</p>

<p>
  <strong>Sqf:</strong>
  <%= @house.sqf %>
</p>

<p>
  <strong>Year:</strong>
  <%= @house.year %>
</p>

<p>
  <strong>Style:</strong>
  <%= @house.style %>
</p>

<p>
  <strong>Price:</strong>
  <%= @house.price %>
</p>

<p>
  <strong>Floors:</strong>
  <%= @house.floors %>
</p>

<p>
  <strong>Basement:</strong>
  <%= @house.basement %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @house.owner %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @house.contact %>
</p>

<p>
  <strong>Potentialbuyers:</strong>
  <%= @house.potentialbuyers %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%#= link_to 'Back', houses_path %>
<%= link_to 'Back to profile page', realtorprofile_path(current_realtor) %>