Program 2 (Ruby on Rails)/config/routes.rb
Rails.application.routes.draw do

  get 'adminprofile/showadmin'
  resources :recompanies
  devise_for :admins, :controllers => {
      :registrations => "admins/registrations",
      :sessions => "admins/sessions",
      :passwords => "admins/passwords",
      :confirmations => "admins/confirmations",
  }

  devise_scope :admin do
    get 'sign_up', to: 'admins/registrations#new'
    get 'sign_in' , to: 'admins/sessions#new'
    delete 'sign_out', to: 'admins/sessions#destroy'
    resources :admins
  end

  #get 'realtorprofile/houses'

  resources :househunterprofile
  get '/showprofile' => "househunterprofile#showprofile", as: :house_hunter_root
  resources :inquiries
  devise_for :house_hunters,  controllers: {sessions: 'house_hunters/sessions'}

  resources :house_hunters
  devise_for :realtors
  resources :houses
   # get '/houses' => "house#index", as: :realtor_root
  # get '/realtorprofile/:current_realtor_id' => "realtorprofile#show", as: :realtor_root
  get '/houses' => "houses#index", as: :realtor_root
  #get '/houses' => "houses#index", as: :house_hunter_root
  #get '/index' => '/app/views/'
  resources :realtorprofile

  get '/admins' => "admins#index"


  root :to => redirect('/homepage.html')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/listinquiries' => "inquiries#listinquiries"
end

Program 2 (Ruby on Rails)/app/controllers/adminprofile_controller.rb
class AdminprofileController < ApplicationController
  def showadmin
  end
end

Program 2 (Ruby on Rails)/app/helpers/adminprofile_helper.rb
module AdminprofileHelper
end

Program 2 (Ruby on Rails)/app/views/adminprofile/showadmin.html.erb
<h2>Select one of the following links</h2>

<h3><%= link_to 'View Houses', houses_path %></h3>
<br>
<h3><%= link_to 'View your inquiries', inquiries_path %></h3>
<br>
<h3><%= link_to 'View Real Estate Companies', recompanies_path %></h3>
<br>
<h3><%= link_to 'View House Hunters', house_hunters_path %></h3>
<br>
<h3><%= link_to 'View Inquiries', listinquiries_path %></h3>
<br>